security:

    providers:
        in_database:
            entity:
                class: App\Entity\Participant
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: in_database
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: home

    encoders:
        App\Entity\Participant:
            algorithm: bcrypt

    access_control:


