security:

    providers:
        in_database:
            entity:
                class: App\Entity\Participant
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: in_database
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: home
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 10
                path:     /

    encoders:
        App\Entity\Participant:
            algorithm: bcrypt

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }



